// <auto-generated />
using System;
using DynamicTranslateDemo.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicTranslateDemo.Migrations
{
    [DbContext(typeof(DummyDBContext))]
    [Migration("20241015014135_intial_translation")]
    partial class intial_translation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DynamicTranslate.DB.OverrideTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entity")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Property")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(3500)
                        .HasColumnType("nvarchar(3500)");

                    b.HasKey("Id");

                    b.HasIndex("Text");

                    b.HasIndex("Entity", "Property", "Key")
                        .IsUnique()
                        .HasFilter("[Entity] IS NOT NULL AND [Property] IS NOT NULL AND [Key] IS NOT NULL");

                    b.ToTable("OverrideTranslations", "Translation");
                });

            modelBuilder.Entity("DynamicTranslate.DB.OverrideTranslationDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("OverrideTranslationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(3500)
                        .HasColumnType("nvarchar(3500)");

                    b.HasKey("Id");

                    b.HasIndex("OverrideTranslationId");

                    b.ToTable("OverrideTranslationDetails", "Translation");
                });

            modelBuilder.Entity("DynamicTranslateDemo.Model.ChildLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MasterLookupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Property2")
                        .HasColumnType("int");

                    b.Property<bool?>("Property3")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MasterLookupId");

                    b.ToTable("ChildLookups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MasterLookupId = 1,
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 2,
                            MasterLookupId = 1,
                            Name = "Oracle"
                        },
                        new
                        {
                            Id = 3,
                            MasterLookupId = 1,
                            Name = "Others"
                        },
                        new
                        {
                            Id = 4,
                            MasterLookupId = 2,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 5,
                            MasterLookupId = 2,
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = 6,
                            MasterLookupId = 2,
                            Name = "Saudi Arabia"
                        });
                });

            modelBuilder.Entity("DynamicTranslateDemo.Model.MasterLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Property2")
                        .HasColumnType("int");

                    b.Property<bool?>("Property3")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("MasterLookups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Software Companies"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Countries"
                        });
                });

            modelBuilder.Entity("DynamicTranslate.DB.OverrideTranslationDetail", b =>
                {
                    b.HasOne("DynamicTranslate.DB.OverrideTranslation", "OverrideTranslation")
                        .WithMany("OverrideTranslationDetails")
                        .HasForeignKey("OverrideTranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OverrideTranslation");
                });

            modelBuilder.Entity("DynamicTranslateDemo.Model.ChildLookup", b =>
                {
                    b.HasOne("DynamicTranslateDemo.Model.MasterLookup", "MasterLookup")
                        .WithMany("ChildLookups")
                        .HasForeignKey("MasterLookupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterLookup");
                });

            modelBuilder.Entity("DynamicTranslate.DB.OverrideTranslation", b =>
                {
                    b.Navigation("OverrideTranslationDetails");
                });

            modelBuilder.Entity("DynamicTranslateDemo.Model.MasterLookup", b =>
                {
                    b.Navigation("ChildLookups");
                });
#pragma warning restore 612, 618
        }
    }
}
